"""First-run wizard: lets users paste their API key into a GUI dialog.

Invoked from cli.py when no .env file is found. Writes the resulting .env to
%APPDATA%\\voice-flow\\.env (or ~/.voice-flow/.env on non-Windows) so the next
launch picks it up automatically — no terminal, no Notepad, no editing files.

Why a separate QApplication: this dialog runs BEFORE the main app boots.
It must terminate cleanly so the overlay's QApplication can start fresh later.
"""
from __future__ import annotations

import logging
import sys
from pathlib import Path

from voice_flow.config import USER_CONFIG_DIR

log = logging.getLogger(__name__)


# ── .env writer ────────────────────────────────────────────────────────


def write_env_file(
    openai_key: str,
    anthropic_key: str | None = None,
    enable_cleanup: bool = False,
    target: Path | None = None,
) -> Path:
    """Write the supplied keys to a .env file. Returns the path written.

    Default target: USER_CONFIG_DIR/.env (creates the directory if needed).
    """
    if target is None:
        USER_CONFIG_DIR.mkdir(parents=True, exist_ok=True)
        target = USER_CONFIG_DIR / ".env"
    else:
        target.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Voice Flow configuration — generated by the first-run wizard.",
        f"OPENAI_API_KEY={openai_key.strip()}",
    ]
    if anthropic_key and anthropic_key.strip():
        lines.append(f"ANTHROPIC_API_KEY={anthropic_key.strip()}")
        if enable_cleanup:
            lines.append("VOICE_FLOW_ENABLE_CLEANUP=1")
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    log.info("First-run config written to %s", target)
    return target


# ── PyQt6 dialog ───────────────────────────────────────────────────────


def run_wizard() -> Path | None:
    """Show the wizard and return the written .env path, or None on cancel.

    Returns None if PyQt6 is unavailable so callers can fall back to text mode.
    """
    try:
        from PyQt6.QtCore import Qt
        from PyQt6.QtGui import QFont
        from PyQt6.QtWidgets import (
            QApplication,
            QCheckBox,
            QDialog,
            QDialogButtonBox,
            QLabel,
            QLineEdit,
            QVBoxLayout,
        )
    except ImportError as ex:
        log.warning("PyQt6 not installed (%s) — cannot show first-run wizard.", ex)
        return None

    app = QApplication.instance()
    owns_app = False
    if app is None:
        app = QApplication(sys.argv if hasattr(sys, "argv") else [])
        owns_app = True

    dlg = QDialog()
    dlg.setWindowTitle("Voice Flow — first-time setup")
    dlg.setMinimumWidth(520)
    dlg.setWindowFlags(dlg.windowFlags() | Qt.WindowType.WindowStaysOnTopHint)

    layout = QVBoxLayout(dlg)
    layout.setContentsMargins(22, 22, 22, 22)
    layout.setSpacing(12)

    title = QLabel("Welcome to Voice Flow")
    title_font = QFont()
    title_font.setPointSize(14)
    title_font.setBold(True)
    title.setFont(title_font)
    layout.addWidget(title)

    intro = QLabel(
        "Paste your OpenAI API key below. Voice Flow uses it for Whisper "
        "transcription only — your key stays on this machine.\n\n"
        "Get a key at https://platform.openai.com/api-keys"
    )
    intro.setWordWrap(True)
    layout.addWidget(intro)

    layout.addWidget(_label("OpenAI API key (required)"))
    openai_input = QLineEdit()
    openai_input.setPlaceholderText("sk-...")
    openai_input.setEchoMode(QLineEdit.EchoMode.Password)
    layout.addWidget(openai_input)

    show_openai = QCheckBox("Show OpenAI key")
    show_openai.toggled.connect(
        lambda checked: openai_input.setEchoMode(
            QLineEdit.EchoMode.Normal if checked else QLineEdit.EchoMode.Password
        )
    )
    layout.addWidget(show_openai)

    layout.addSpacing(8)
    layout.addWidget(_label("Anthropic API key (optional — enables Claude cleanup)"))
    anth_input = QLineEdit()
    anth_input.setPlaceholderText("sk-ant-api03-...   (leave empty to skip)")
    anth_input.setEchoMode(QLineEdit.EchoMode.Password)
    layout.addWidget(anth_input)

    show_anth = QCheckBox("Show Anthropic key")
    show_anth.toggled.connect(
        lambda checked: anth_input.setEchoMode(
            QLineEdit.EchoMode.Normal if checked else QLineEdit.EchoMode.Password
        )
    )
    layout.addWidget(show_anth)

    enable_cleanup = QCheckBox(
        "Enable Claude cleanup (fix typos and proper nouns after transcription)"
    )
    layout.addWidget(enable_cleanup)

    layout.addSpacing(8)
    target_label = QLabel(
        f"Saved to: {USER_CONFIG_DIR / '.env'}\nYou can edit this file later."
    )
    target_label.setStyleSheet("color: #666; font-size: 11px;")
    layout.addWidget(target_label)

    error_label = QLabel("")
    error_label.setStyleSheet("color: #C0392B; font-weight: bold;")
    error_label.setVisible(False)
    layout.addWidget(error_label)

    buttons = QDialogButtonBox(
        QDialogButtonBox.StandardButton.Ok | QDialogButtonBox.StandardButton.Cancel
    )
    layout.addWidget(buttons)

    result_holder: dict = {"path": None}

    def on_accept() -> None:
        openai_key = openai_input.text().strip()
        if not openai_key:
            error_label.setText("OpenAI API key is required.")
            error_label.setVisible(True)
            return
        if not openai_key.startswith("sk-"):
            error_label.setText("OpenAI keys start with 'sk-'. Please double-check.")
            error_label.setVisible(True)
            return
        try:
            path = write_env_file(
                openai_key=openai_key,
                anthropic_key=anth_input.text(),
                enable_cleanup=enable_cleanup.isChecked(),
            )
            result_holder["path"] = path
            dlg.accept()
        except OSError as ex:
            error_label.setText(f"Could not write config: {ex}")
            error_label.setVisible(True)

    buttons.accepted.connect(on_accept)
    buttons.rejected.connect(dlg.reject)

    dlg.exec()
    if owns_app:
        # Discard our QApplication so the overlay can build its own later.
        # Do NOT call app.quit() — it leaves the event loop in a bad state.
        del app

    return result_holder["path"]


def _label(text: str):
    """Small helper — returns a QLabel without importing PyQt at module top-level."""
    from PyQt6.QtWidgets import QLabel
    lbl = QLabel(text)
    lbl.setStyleSheet("font-weight: 600;")
    return lbl
